spring:
  datasource:
    url: jdbc:oracle:thin:@smarttradersob-22.c4gebpgnh17l.us-east-1.rds.amazonaws.com:1521:SOB
    username: EFOREX231
    password: Y8agR2k2

app:
  security:
    roles: >
      TRADER
    secret:
      key: wKpm8u8ZJAX7JZapN7p7CE7G3Q34Be2ZwuQQgWZsLcWy0IJNwGpU6yzX65GcRPEBbSHqkCfTAKAjIYl1NPbjnCijxidMaMsRdFnZrhQ+H3Nh2WbKtAqs3E7+MBk98hhJpS3eXArsjLiWqtD3aLuZYlnJeUqovjD+LdY6mpx4arsk9Wq7RgxEwdpS/FwsIQK79eNCzC/lZ9ACZyd0zFQBUYbzTZVK6xcUsEAg3Q==
    token: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxMDEwOTc4OSIsInJvbGUiOiJUUkFERVIiLCJpc3MiOiJhdXRoLWxpZ2h0LmF1dGhlbnRpY2F0ZWQtdHJhZGVyIiwiaWF0IjoxNjg3ODY2MzcwLCJleHAiOjE2ODg0NzExNzB9.RIhgu1jOsDOhkfrK3rMw-26VJq2pq0uWdiEU5w6conyFV8jP8wulXTC5IVvCulnBkGsrC20974rk4supZ-5sdA
  target: localhost:8080